pub mod planner;

pub use crate::sql_parser::ast;

use std::sync::Arc;

use arrow::{
    array::ArrayRef,
    datatypes::{DataType, Schema},
};

use crate::planner::ast::operators::BinaryOperator;

/// Represents dynamic scalar literal values in expressions
pub enum ScalarValue {
    Null(DataType),
    Boolean(Option<bool>),
    Int32(Option<i32>),
    Int64(Option<i64>),
    Float64(Option<f64>),
    Utf8(Option<String>),
}

impl ScalarValue {
    pub fn to_arrow(&self) -> ArrayRef {
        todo!("implement me")
    }
}

pub enum AggregationFn {
    Sum,
    Count,
    Min,
    Max,
    Avg,
}

pub enum JoinType {
    Inner,
    Left,
    Right,
    Full,
}

pub enum LogicalExpr {
    /// A named reference to a column (e.g., `id`, `name`)
    Column(String),
    /// A literal constant value (e.g., `42`, `"Alice"`)
    Literal(ScalarValue),
    BinaryOp {
        left: Box<LogicalExpr>,
        op: BinaryOperator,
        right: Box<LogicalExpr>,
    },
    /// An aggregate function call (e.g., `SUM(amount)`, `COUNT(*)`)
    Aggregation {
        op: AggregationFn,
        args: Vec<LogicalExpr>,
    },
    Alias {
        expr: Box<LogicalExpr>,
        alias: String,
    },
}

pub struct LogicalColumnDef {
    pub name: String,
    pub data_type: DataType,
}

pub enum LogicalPlan {
    // Query + Relational
    /// Reads data from a physical table partition, optionally pruning columns
    Scan {
        table_name: String,
        schema: Arc<Schema>,
        projections: Option<Vec<String>>,
    },

    /// Evaluates predicate and filters rows (representing `WHERE` clauses)
    Filter {
        predicate: LogicalExpr,
        input: Box<LogicalPlan>,
    },

    /// Evaluates expressions and shapes the output columns (representing `SELECT` lists)
    Projection {
        exprs: Vec<LogicalExpr>,
        input: Box<LogicalPlan>,
        schema: Arc<Schema>,
    },

    /// Joins two datasets (representing `JOIN` chains)
    HashJoin {
        left: Box<LogicalPlan>,
        right: Box<LogicalPlan>,
        on: Vec<(LogicalExpr, LogicalExpr)>,
        join_type: JoinType,
        schema: Arc<Schema>,
    },

    /// Aggregates and groups data (representing `GROUP BY` and aggregate selections)
    Aggregate {
        group_by: Vec<LogicalExpr>,
        input: Box<LogicalPlan>,
        schema: Arc<Schema>,
    },

    /// Sorts rows by expressions (representing `ORDER BY` clauses)
    Sort {
        sort_exprs: Vec<LogicalExpr>,
        input: Box<LogicalPlan>,
    },

    /// Slices the relation (representing `LIMIT` and `OFFSET` clauses)
    Limit {
        limit: usize,
        offset: usize,
        input: Box<LogicalPlan>,
    },

    // DML
    /// Inserts the rows generated by a query plan into a target table (representing INSERT)
    Insert {
        table_name: String,
        columns: Vec<String>,
        input: Box<LogicalPlan>,
    },

    /// Updates matching rows in a table (representing `UPDATE`)
    Update {
        table_name: String,
        assignments: Vec<(String, LogicalExpr)>,
        selection: Option<LogicalExpr>,
    },

    /// Deletes matching rows from a table (representing `DELETE`)
    Delete {
        table_name: String,
        selection: Option<LogicalExpr>,
    },

    // DDL
    /// Registers a new table schema in the catalog (representing `CREATE TABLE`)
    CreateTable {
        table_name: String,
        columns: Vec<LogicalColumnDef>,
    },

    ShowTables,
}
