// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"github.com/datnguyenzzz/nogodb/lib/go-sstable/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockILayoutWriter creates a new instance of MockILayoutWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILayoutWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILayoutWriter {
	mock := &MockILayoutWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILayoutWriter is an autogenerated mock type for the ILayoutWriter type
type MockILayoutWriter struct {
	mock.Mock
}

type MockILayoutWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILayoutWriter) EXPECT() *MockILayoutWriter_Expecter {
	return &MockILayoutWriter_Expecter{mock: &_m.Mock}
}

// Abort provides a mock function for the type MockILayoutWriter
func (_mock *MockILayoutWriter) Abort() {
	_mock.Called()
	return
}

// MockILayoutWriter_Abort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abort'
type MockILayoutWriter_Abort_Call struct {
	*mock.Call
}

// Abort is a helper method to define mock.On call
func (_e *MockILayoutWriter_Expecter) Abort() *MockILayoutWriter_Abort_Call {
	return &MockILayoutWriter_Abort_Call{Call: _e.mock.On("Abort")}
}

func (_c *MockILayoutWriter_Abort_Call) Run(run func()) *MockILayoutWriter_Abort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockILayoutWriter_Abort_Call) Return() *MockILayoutWriter_Abort_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockILayoutWriter_Abort_Call) RunAndReturn(run func()) *MockILayoutWriter_Abort_Call {
	_c.Run(run)
	return _c
}

// Finish provides a mock function for the type MockILayoutWriter
func (_mock *MockILayoutWriter) Finish() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILayoutWriter_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockILayoutWriter_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
func (_e *MockILayoutWriter_Expecter) Finish() *MockILayoutWriter_Finish_Call {
	return &MockILayoutWriter_Finish_Call{Call: _e.mock.On("Finish")}
}

func (_c *MockILayoutWriter_Finish_Call) Run(run func()) *MockILayoutWriter_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockILayoutWriter_Finish_Call) Return(err error) *MockILayoutWriter_Finish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILayoutWriter_Finish_Call) RunAndReturn(run func() error) *MockILayoutWriter_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// WritePhysicalBlock provides a mock function for the type MockILayoutWriter
func (_mock *MockILayoutWriter) WritePhysicalBlock(b common.PhysicalBlock) (common.BlockHandle, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for WritePhysicalBlock")
	}

	var r0 common.BlockHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(common.PhysicalBlock) (common.BlockHandle, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func(common.PhysicalBlock) common.BlockHandle); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(common.BlockHandle)
	}
	if returnFunc, ok := ret.Get(1).(func(common.PhysicalBlock) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILayoutWriter_WritePhysicalBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePhysicalBlock'
type MockILayoutWriter_WritePhysicalBlock_Call struct {
	*mock.Call
}

// WritePhysicalBlock is a helper method to define mock.On call
//   - b common.PhysicalBlock
func (_e *MockILayoutWriter_Expecter) WritePhysicalBlock(b interface{}) *MockILayoutWriter_WritePhysicalBlock_Call {
	return &MockILayoutWriter_WritePhysicalBlock_Call{Call: _e.mock.On("WritePhysicalBlock", b)}
}

func (_c *MockILayoutWriter_WritePhysicalBlock_Call) Run(run func(b common.PhysicalBlock)) *MockILayoutWriter_WritePhysicalBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.PhysicalBlock
		if args[0] != nil {
			arg0 = args[0].(common.PhysicalBlock)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILayoutWriter_WritePhysicalBlock_Call) Return(blockHandle common.BlockHandle, err error) *MockILayoutWriter_WritePhysicalBlock_Call {
	_c.Call.Return(blockHandle, err)
	return _c
}

func (_c *MockILayoutWriter_WritePhysicalBlock_Call) RunAndReturn(run func(b common.PhysicalBlock) (common.BlockHandle, error)) *MockILayoutWriter_WritePhysicalBlock_Call {
	_c.Call.Return(run)
	return _c
}

// WriteRawBytes provides a mock function for the type MockILayoutWriter
func (_mock *MockILayoutWriter) WriteRawBytes(b []byte) (common.BlockHandle, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for WriteRawBytes")
	}

	var r0 common.BlockHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (common.BlockHandle, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) common.BlockHandle); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(common.BlockHandle)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILayoutWriter_WriteRawBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteRawBytes'
type MockILayoutWriter_WriteRawBytes_Call struct {
	*mock.Call
}

// WriteRawBytes is a helper method to define mock.On call
//   - b []byte
func (_e *MockILayoutWriter_Expecter) WriteRawBytes(b interface{}) *MockILayoutWriter_WriteRawBytes_Call {
	return &MockILayoutWriter_WriteRawBytes_Call{Call: _e.mock.On("WriteRawBytes", b)}
}

func (_c *MockILayoutWriter_WriteRawBytes_Call) Run(run func(b []byte)) *MockILayoutWriter_WriteRawBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILayoutWriter_WriteRawBytes_Call) Return(blockHandle common.BlockHandle, err error) *MockILayoutWriter_WriteRawBytes_Call {
	_c.Call.Return(blockHandle, err)
	return _c
}

func (_c *MockILayoutWriter_WriteRawBytes_Call) RunAndReturn(run func(b []byte) (common.BlockHandle, error)) *MockILayoutWriter_WriteRawBytes_Call {
	_c.Call.Return(run)
	return _c
}
