// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockILayoutReader creates a new instance of MockILayoutReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILayoutReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILayoutReader {
	mock := &MockILayoutReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILayoutReader is an autogenerated mock type for the ILayoutReader type
type MockILayoutReader struct {
	mock.Mock
}

type MockILayoutReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILayoutReader) EXPECT() *MockILayoutReader_Expecter {
	return &MockILayoutReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockILayoutReader
func (_mock *MockILayoutReader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILayoutReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockILayoutReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockILayoutReader_Expecter) Close() *MockILayoutReader_Close_Call {
	return &MockILayoutReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockILayoutReader_Close_Call) Run(run func()) *MockILayoutReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockILayoutReader_Close_Call) Return(err error) *MockILayoutReader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILayoutReader_Close_Call) RunAndReturn(run func() error) *MockILayoutReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type MockILayoutReader
func (_mock *MockILayoutReader) ReadAt(p []byte, off uint64) error {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, uint64) error); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILayoutReader_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockILayoutReader_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off uint64
func (_e *MockILayoutReader_Expecter) ReadAt(p interface{}, off interface{}) *MockILayoutReader_ReadAt_Call {
	return &MockILayoutReader_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *MockILayoutReader_ReadAt_Call) Run(run func(p []byte, off uint64)) *MockILayoutReader_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILayoutReader_ReadAt_Call) Return(err error) *MockILayoutReader_ReadAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILayoutReader_ReadAt_Call) RunAndReturn(run func(p []byte, off uint64) error) *MockILayoutReader_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}
