// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package row_block

import (
	common0 "github.com/datnguyenzzz/nogodb/lib/common"
	"github.com/datnguyenzzz/nogodb/lib/go-bytesbufferpool/predictable_size"
	"github.com/datnguyenzzz/nogodb/lib/go-sstable/common"
	"github.com/datnguyenzzz/nogodb/lib/go-sstable/options"
	"github.com/datnguyenzzz/nogodb/lib/go-sstable/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIBlockReader creates a new instance of MockIBlockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBlockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBlockReader {
	mock := &MockIBlockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBlockReader is an autogenerated mock type for the IBlockReader type
type MockIBlockReader struct {
	mock.Mock
}

type MockIBlockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBlockReader) EXPECT() *MockIBlockReader_Expecter {
	return &MockIBlockReader_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockIBlockReader
func (_mock *MockIBlockReader) Init(bpool *predictable_size.PredictablePool, fr storage.ILayoutReader, cacheOpts *options.CacheOptions) {
	_mock.Called(bpool, fr, cacheOpts)
	return
}

// MockIBlockReader_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockIBlockReader_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - bpool *predictable_size.PredictablePool
//   - fr storage.ILayoutReader
//   - cacheOpts *options.CacheOptions
func (_e *MockIBlockReader_Expecter) Init(bpool interface{}, fr interface{}, cacheOpts interface{}) *MockIBlockReader_Init_Call {
	return &MockIBlockReader_Init_Call{Call: _e.mock.On("Init", bpool, fr, cacheOpts)}
}

func (_c *MockIBlockReader_Init_Call) Run(run func(bpool *predictable_size.PredictablePool, fr storage.ILayoutReader, cacheOpts *options.CacheOptions)) *MockIBlockReader_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *predictable_size.PredictablePool
		if args[0] != nil {
			arg0 = args[0].(*predictable_size.PredictablePool)
		}
		var arg1 storage.ILayoutReader
		if args[1] != nil {
			arg1 = args[1].(storage.ILayoutReader)
		}
		var arg2 *options.CacheOptions
		if args[2] != nil {
			arg2 = args[2].(*options.CacheOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBlockReader_Init_Call) Return() *MockIBlockReader_Init_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBlockReader_Init_Call) RunAndReturn(run func(bpool *predictable_size.PredictablePool, fr storage.ILayoutReader, cacheOpts *options.CacheOptions)) *MockIBlockReader_Init_Call {
	_c.Run(run)
	return _c
}

// Read provides a mock function for the type MockIBlockReader
func (_mock *MockIBlockReader) Read(bh *common.BlockHandle, kind common0.BlockKind) (*common0.InternalLazyValue, error) {
	ret := _mock.Called(bh, kind)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *common0.InternalLazyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle, common0.BlockKind) (*common0.InternalLazyValue, error)); ok {
		return returnFunc(bh, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle, common0.BlockKind) *common0.InternalLazyValue); ok {
		r0 = returnFunc(bh, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common0.InternalLazyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*common.BlockHandle, common0.BlockKind) error); ok {
		r1 = returnFunc(bh, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBlockReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockIBlockReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - bh *common.BlockHandle
//   - kind common0.BlockKind
func (_e *MockIBlockReader_Expecter) Read(bh interface{}, kind interface{}) *MockIBlockReader_Read_Call {
	return &MockIBlockReader_Read_Call{Call: _e.mock.On("Read", bh, kind)}
}

func (_c *MockIBlockReader_Read_Call) Run(run func(bh *common.BlockHandle, kind common0.BlockKind)) *MockIBlockReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.BlockHandle
		if args[0] != nil {
			arg0 = args[0].(*common.BlockHandle)
		}
		var arg1 common0.BlockKind
		if args[1] != nil {
			arg1 = args[1].(common0.BlockKind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockReader_Read_Call) Return(internalLazyValue *common0.InternalLazyValue, err error) *MockIBlockReader_Read_Call {
	_c.Call.Return(internalLazyValue, err)
	return _c
}

func (_c *MockIBlockReader_Read_Call) RunAndReturn(run func(bh *common.BlockHandle, kind common0.BlockKind) (*common0.InternalLazyValue, error)) *MockIBlockReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadThroughCache provides a mock function for the type MockIBlockReader
func (_mock *MockIBlockReader) ReadThroughCache(bh *common.BlockHandle, kind common0.BlockKind) (*common0.InternalLazyValue, error) {
	ret := _mock.Called(bh, kind)

	if len(ret) == 0 {
		panic("no return value specified for ReadThroughCache")
	}

	var r0 *common0.InternalLazyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle, common0.BlockKind) (*common0.InternalLazyValue, error)); ok {
		return returnFunc(bh, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle, common0.BlockKind) *common0.InternalLazyValue); ok {
		r0 = returnFunc(bh, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common0.InternalLazyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*common.BlockHandle, common0.BlockKind) error); ok {
		r1 = returnFunc(bh, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBlockReader_ReadThroughCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadThroughCache'
type MockIBlockReader_ReadThroughCache_Call struct {
	*mock.Call
}

// ReadThroughCache is a helper method to define mock.On call
//   - bh *common.BlockHandle
//   - kind common0.BlockKind
func (_e *MockIBlockReader_Expecter) ReadThroughCache(bh interface{}, kind interface{}) *MockIBlockReader_ReadThroughCache_Call {
	return &MockIBlockReader_ReadThroughCache_Call{Call: _e.mock.On("ReadThroughCache", bh, kind)}
}

func (_c *MockIBlockReader_ReadThroughCache_Call) Run(run func(bh *common.BlockHandle, kind common0.BlockKind)) *MockIBlockReader_ReadThroughCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.BlockHandle
		if args[0] != nil {
			arg0 = args[0].(*common.BlockHandle)
		}
		var arg1 common0.BlockKind
		if args[1] != nil {
			arg1 = args[1].(common0.BlockKind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockReader_ReadThroughCache_Call) Return(internalLazyValue *common0.InternalLazyValue, err error) *MockIBlockReader_ReadThroughCache_Call {
	_c.Call.Return(internalLazyValue, err)
	return _c
}

func (_c *MockIBlockReader_ReadThroughCache_Call) RunAndReturn(run func(bh *common.BlockHandle, kind common0.BlockKind) (*common0.InternalLazyValue, error)) *MockIBlockReader_ReadThroughCache_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockIBlockReader
func (_mock *MockIBlockReader) Release() {
	_mock.Called()
	return
}

// MockIBlockReader_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockIBlockReader_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *MockIBlockReader_Expecter) Release() *MockIBlockReader_Release_Call {
	return &MockIBlockReader_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *MockIBlockReader_Release_Call) Run(run func()) *MockIBlockReader_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIBlockReader_Release_Call) Return() *MockIBlockReader_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBlockReader_Release_Call) RunAndReturn(run func()) *MockIBlockReader_Release_Call {
	_c.Run(run)
	return _c
}
