// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package row_block

import (
	common0 "github.com/datnguyenzzz/nogodb/lib/common"
	"github.com/datnguyenzzz/nogodb/lib/go-sstable/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIBlockCacheWrapper creates a new instance of MockIBlockCacheWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBlockCacheWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBlockCacheWrapper {
	mock := &MockIBlockCacheWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBlockCacheWrapper is an autogenerated mock type for the IBlockCacheWrapper type
type MockIBlockCacheWrapper struct {
	mock.Mock
}

type MockIBlockCacheWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBlockCacheWrapper) EXPECT() *MockIBlockCacheWrapper_Expecter {
	return &MockIBlockCacheWrapper_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIBlockCacheWrapper
func (_mock *MockIBlockCacheWrapper) Close() {
	_mock.Called()
	return
}

// MockIBlockCacheWrapper_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIBlockCacheWrapper_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIBlockCacheWrapper_Expecter) Close() *MockIBlockCacheWrapper_Close_Call {
	return &MockIBlockCacheWrapper_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIBlockCacheWrapper_Close_Call) Run(run func()) *MockIBlockCacheWrapper_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIBlockCacheWrapper_Close_Call) Return() *MockIBlockCacheWrapper_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBlockCacheWrapper_Close_Call) RunAndReturn(run func()) *MockIBlockCacheWrapper_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockIBlockCacheWrapper
func (_mock *MockIBlockCacheWrapper) Get(bh *common.BlockHandle) (*common0.InternalLazyValue, error) {
	ret := _mock.Called(bh)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *common0.InternalLazyValue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle) (*common0.InternalLazyValue, error)); ok {
		return returnFunc(bh)
	}
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle) *common0.InternalLazyValue); ok {
		r0 = returnFunc(bh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common0.InternalLazyValue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*common.BlockHandle) error); ok {
		r1 = returnFunc(bh)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBlockCacheWrapper_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIBlockCacheWrapper_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - bh *common.BlockHandle
func (_e *MockIBlockCacheWrapper_Expecter) Get(bh interface{}) *MockIBlockCacheWrapper_Get_Call {
	return &MockIBlockCacheWrapper_Get_Call{Call: _e.mock.On("Get", bh)}
}

func (_c *MockIBlockCacheWrapper_Get_Call) Run(run func(bh *common.BlockHandle)) *MockIBlockCacheWrapper_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.BlockHandle
		if args[0] != nil {
			arg0 = args[0].(*common.BlockHandle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIBlockCacheWrapper_Get_Call) Return(internalLazyValue *common0.InternalLazyValue, err error) *MockIBlockCacheWrapper_Get_Call {
	_c.Call.Return(internalLazyValue, err)
	return _c
}

func (_c *MockIBlockCacheWrapper_Get_Call) RunAndReturn(run func(bh *common.BlockHandle) (*common0.InternalLazyValue, error)) *MockIBlockCacheWrapper_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockIBlockCacheWrapper
func (_mock *MockIBlockCacheWrapper) Set(bh *common.BlockHandle, val *common0.InternalLazyValue) error {
	ret := _mock.Called(bh, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*common.BlockHandle, *common0.InternalLazyValue) error); ok {
		r0 = returnFunc(bh, val)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBlockCacheWrapper_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIBlockCacheWrapper_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - bh *common.BlockHandle
//   - val *common0.InternalLazyValue
func (_e *MockIBlockCacheWrapper_Expecter) Set(bh interface{}, val interface{}) *MockIBlockCacheWrapper_Set_Call {
	return &MockIBlockCacheWrapper_Set_Call{Call: _e.mock.On("Set", bh, val)}
}

func (_c *MockIBlockCacheWrapper_Set_Call) Run(run func(bh *common.BlockHandle, val *common0.InternalLazyValue)) *MockIBlockCacheWrapper_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *common.BlockHandle
		if args[0] != nil {
			arg0 = args[0].(*common.BlockHandle)
		}
		var arg1 *common0.InternalLazyValue
		if args[1] != nil {
			arg1 = args[1].(*common0.InternalLazyValue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBlockCacheWrapper_Set_Call) Return(err error) *MockIBlockCacheWrapper_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBlockCacheWrapper_Set_Call) RunAndReturn(run func(bh *common.BlockHandle, val *common0.InternalLazyValue) error) *MockIBlockCacheWrapper_Set_Call {
	_c.Call.Return(run)
	return _c
}
